"use strict";
/**
 * Pixel regions inside res://assets/sprites.png. The atlas is generated by
 * tools/build_atlas.py from the CC-BY "Bomb Party" sheet (see
 * assets/third_party/ATTRIBUTION.md); layouts must stay in sync with it.
 *
 * Tiles in row 0 (floor, wall, crate, bush) are normalized grayscale so the
 * renderer can modulate them with each map's theme colors.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CHAR_VARIANTS = exports.SPR = exports.CELL = exports.ATLAS_PATH = void 0;
exports.bombFrame = bombFrame;
exports.charFrame = charFrame;
exports.ATLAS_PATH = 'res://assets/sprites.png';
/** Atlas cell size in source pixels. */
exports.CELL = 16;
const cell = (c, r) => ({
    x: c * exports.CELL,
    y: r * exports.CELL,
    w: exports.CELL,
    h: exports.CELL,
});
exports.SPR = {
    floorA: cell(0, 0),
    floorB: cell(1, 0),
    wall: cell(2, 0),
    crate: cell(3, 0),
    shadow: cell(4, 0),
    ring: cell(5, 0),
    panel: cell(6, 0),
    bolt: cell(7, 0),
    bush: cell(8, 0),
    flameCenter: cell(0, 1),
    flameH: cell(1, 1),
    flameTipL: cell(2, 1),
    flameTipR: cell(3, 1),
    flameV: cell(4, 1),
    flameTipU: cell(5, 1),
    flameTipD: cell(6, 1),
    flameBall: cell(7, 1),
    flameBurst: cell(8, 1),
};
/** One hooded-goblin recolor per player slot (robe = PLAYER_COLORS[slot]). */
exports.CHAR_VARIANTS = 6;
/** Bomb fuse animation, 6 frames. */
function bombFrame(index) {
    return cell(((index % 6) + 6) % 6, 2);
}
/**
 * Character frame lookup. `step` is a walk-cycle counter (any non-negative
 * integer); pass 0 when idle.
 */
function charFrame(variant, facing, step) {
    const row = 3 + (((variant % exports.CHAR_VARIANTS) + exports.CHAR_VARIANTS) % exports.CHAR_VARIANTS);
    switch (facing) {
        case 'down':
            return cell(step % 4, row);
        case 'right':
            return cell(4 + (step % 4), row);
        case 'up':
            return cell(8 + (step % 2), row);
        case 'left':
            return cell(10 + (step % 4), row);
    }
}
